### PR TITLE
Rename drake_cloc.py to git_cloc for more clarity

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/seancurtis-tri/git_cloc/8)

### CODE REVIEW

**Review by SeanCurtis-TRI — APPROVED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/git_cloc/8#-:-MWo4tf9D3rMrCcjRjnc:bmxilld)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by SeanCurtis-TRI — APPROVED** [review]
I think I made a *bad* decision in accepting the other PR and this will require a rebase.  :-/ Sorry.

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/git_cloc/8#-:-MWo5AhS3bVlBmoYjrMS:bdlt1d4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
No worries! Should be easy

**Comment by EricCousineau-TRI** [comment]
Done! Took a whopping 30sec to rebase :P

**Review by SeanCurtis-TRI — APPROVED** [review]
THanks

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/git_cloc/8#-:-MWo_3ERC6Kl2MzI2tez:bz6yr66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Pull request merged**
